version: '3'

services:
  postgres:
    container_name: postgres-service
    build:
      context: .
      dockerfile: Dockerfile.development
    image: "postgres-service"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=Library
      - POSTGRES_HOST_AUTH_METHOD=trust


  library_app:
    container_name: library-app
    build:
      context: LibraryMVC
      dockerfile: Dockerfile.development

    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/Library
    image: 'library-app'
    ports:
      - "8080:8080"
    depends_on:
      - postgres


  users_app:
    container_name: users-app
    build:
      context: users-app
      dockerfile: Dockerfile.development

    environment:
      - PORT=8085
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/Library
    image: 'users-app'
    ports:
      - "8085:8085"
    depends_on:
      - postgres